### ISSUE TITLE
CSS seems to destroy ordered list

### ISSUE THREAD

**Issue by itteerde** [Artemystra/eclipsephase#68]
While generally the numbered lists (ol) do work in ep2e they do not. I assume something in your css does make them invalid (I think it is negative spaces moving the numbers out of rendered space). Would be nice if they worked. While there is no TinyMCE use on items or such, it would be nice if it worked on Journals. (ul) works, (ol) does not.

**Comment by Artemystra** [comment]
Hey there, can you provide me with a screenshot of the bug? Would help a lot to understand the issue better.

**Comment by itteerde** [comment]
![image](https://github.com/Artemystra/eclipsephase/assets/8367477/480597fc-b110-4af0-bee6-06960ad52c00)

**Comment by Artemystra** [comment]
Ah, we‘re talking editor! Yes I noticed this already. I believe it‘s not broken bit the css is defined as „do not show numbers“. I will fix this in the next update.
