### ISSUE TITLE
Restore Rest (All Players) Button

### ISSUE THREAD

**Issue by herrozerro** [Artemystra/eclipsephase#71]
I get what the feature is trying to do, it will refresh active sheets attached to players.  But I was just running a session with multiple fork sheets per person and it was a hassle to reset all of the sheets manually.  Perhaps another button called Restore Rest (All PC Sheets)?

**Comment by Artemystra** [comment]
This is possible, but it would limit the GM to use Player sheets if they want to. But in general this is possible and easily to be added to the urrent system.

**Comment by herrozerro** [comment]
Okay I can see the issue.  What about allowing players to have access to the reset test button?  In general I trust my players and would like them to have full control of their sheets

**Comment by johnhelmuth** [comment]
I think having a UI element that pops up a window with a list of player sheets each with a checkbox. The current players' sheets would be checked already. The GM could check the additional sheets they want to "Restore rest", and then clicks the action button to do the thing.

**Comment by Artemystra** [comment]
A fix for this has released with v1.0.2
