### ISSUE TITLE
Melee damage mod is being added regardless of weapon type

### ISSUE THREAD

**Issue by cdlight62** [Artemystra/eclipsephase#76]
Ware such as Muscle Augmentation that adds extra melee damage is also being added to ranged damage rolls.

**Comment by PhDaveMil** [comment]
I would also like to have this fixed! Noticed today that "lethal" was applying its mod to everything.

**Comment by Artemystra** [comment]
Hey there,

how do I reproduce this? Having a character with "lethal" and shooting any weapon?

If so there's a good chance that this will be fixed very soon as I just refactored the whole dice roll system.

**Comment by Artemystra** [comment]
This has been fixed with the current release
